# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
