# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hours_worked',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
